FROM golang:alpine3.18 As builder

WORKDIR /usr/go/src/app

COPY . .

RUN go mod init full-cycle-rocks && \
    go build full-cycle-rocks.go


FROM scratch
WORKDIR /usr/go/src/app
COPY --from=builder /usr/go/src/app .
CMD ["./full-cycle-rocks"]
